theme: jekyll-theme-cayman
title: VaMusaka's Anecdotes
description: "Tolerated failure imprints learning better than success." [__Dave Snowden]. Here is where l share the little knowledge l have earned in my few years of tech. 
